// Mocks generated by Mockito 5.4.4 from annotations
// in github_repository_search_flutter/test/presentation/page/search_repositories/cubit/search_repositories_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:github_repository_search_flutter/domain/github_repositories/model/github_repository_data.dart'
    as _i2;
import 'package:github_repository_search_flutter/domain/github_repositories/use_case/search_repositories_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGithubRepositoryData_0 extends _i1.SmartFake
    implements _i2.GithubRepositoryData {
  _FakeGithubRepositoryData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SearchRepositoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepositoriesUseCase extends _i1.Mock
    implements _i3.SearchRepositoriesUseCase {
  MockSearchRepositoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GithubRepositoryData> call(
    String? query,
    int? page, {
    int? perPage = 4,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            query,
            page,
          ],
          {#perPage: perPage},
        ),
        returnValue: _i4.Future<_i2.GithubRepositoryData>.value(
            _FakeGithubRepositoryData_0(
          this,
          Invocation.method(
            #call,
            [
              query,
              page,
            ],
            {#perPage: perPage},
          ),
        )),
      ) as _i4.Future<_i2.GithubRepositoryData>);
}
